// Generated by CoffeeScript 1.7.1
(function() {
  var HydraServer, server;

  HydraServer = require('./HydraServer');

  server = new HydraServer();

  server.startServer();

}).call(this);

//# sourceMappingURL=server.map
